### ISSUE TITLE
Use of csdid with individual level data but school treatment 

### ISSUE THREAD

**Issue by carmenquezada** [friosavila/csdid_drdid#26]
Hi!
I'm trying to use the csdid command to estimate this specification:
$$y_{ist}=\beta*T_{st}+\lamda_s+\lambda_t+\varepsilon_{ist}$$
I have two years of pre-treatment, then three groups are treated sequentially in the next three years.
As you can see in the specification, my data is at the individual level. In addition, I'm using repeated cross-section data by year, and my treatment varies at the school level (not at the individual level).  To implement this estimate with csdid command, I don't need to specify _ivar_ (because of repeated cross-sections). However, because I'm thinking in a TWFE estimator, I would like to have school fixed effects (since my treatment varies at the school level). Maybe it is not correct to think of the csdid estimator as a fixed effect estimator. I don't know how to "add" these school fixed effects to the commands' options (I have more than 10,000 schools).
Thanks for your help!

**Comment by friosavila** [comment]
Unfortunately youcant.
Based on what you describe you have treatment by school. So adding school
FE would be reasonable in a regression framework, but it is not feasible in
CSDID framework.
The only ways i can think of using that information is to use repeated
crossection data, and cluster by school.
Alternatively, you can collapse your data at the school level, and then use
school as fixed effects.
Otherwise, you may want to think in terms of Garnder(2021) or Wooldridge
(2021) and use regression analysis to add school fixed effects, year fixed
effects,
and full interactions between years and treatment years
